
const data = {
    products: [
        {
            id: 1,
            name: 'Tippy',
            slug: 'tippy',
            description: 'A cool app by Jakob Rössner',
            image: 'assets/images/tippy.png',
            categories: ['app', 'mobile', 'free'],
            price: 0,
            brand: 'Jakob Rössner',
            rating: 5,
            numReviews: 1132,
            countInStock: 'unlimited',
        },
        {
            id: 2,
            name: 'Bigger Number Game',
            slug: 'bigger-number-game',
            description: 'A cool game by Jakob Rössner',
            image: 'assets/images/bigger-number-game.png',
            categories: ['game', 'mobile', 'free'],
            price: 0,
            brand: 'Jakob Rössner',
            rating: 5,
            numReviews: 2467,
            countInStock: 'unlimited',
        },
        {
            id: 3,
            name: 'Uncraftables',
            slug: 'uncraftables',
            description: 'A cool minecraft modification by Jakob Rössner',
            image: 'assets/images/uncraftables.png',
            categories: ['mod', 'minecraft', 'free'],
            price: 0,
            brand: 'Jakob Rössner',
            rating: 5,
            numReviews: 123,
            countInStock: 'unlimited',
        },
        {
            id: 4,
            name: 'Coca Cola Classic',
            slug: 'coca-cola-classic',
            description: 'A cool drink by Coca Cola',
            image: 'assets/images/coca-cola-classic.png',
            categories: ['drink', 'food', 'premium'],
            price: 5.99,
            brand: 'Coca Cola',
            rating: 5,
            numReviews: 438,
            countInStock: 10,
        },
        {
          id: 5,
          name: 'Coca Cola Zero',
          slug: 'coca-cola-zero',
          description: 'A cool drink by Coca Cola with Zero Sugar',
          image: 'assets/images/coca-cola-zero.png',
          categories: ['drink', 'food', 'premium'],
          price: 5.99,
          brand: 'Coca Cola',
          rating: 5,
          numReviews: 592,
          countInStock: 10,
        },
        {
            id: 6,
            name: 'Rode NT1-A',
            slug: 'rode-nt1-a',
            description: 'A cool microphone by Rode',
            image: 'assets/images/rode-nt1-a.png',
            categories: ['microphone', 'audio', 'premium'],
            price: 299.99,
            brand: 'Rode',
            rating: 5,
            numReviews: 9054,
            countInStock: 5,
        }
    ]
};

export default data;